version: 2
jobs:
  build:
    docker:
    - image: circleci/golang:1.9

    working_directory: /go/src/github.com/fujitsueos/sql-migrate

    steps:
    - checkout
    - run:
        name: Install dependencies
        command: |
          go get -v github.com/golang/dep/cmd/dep
          curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | bash -s v1.9.1
          dep ensure -v -vendor-only

    - run:
        name: Lint
        command: golangci-lint run -v

    - run:
        name: Test
        command: go test -race -cover ./...

workflows:
 version: 2
 build:
   jobs:
     - build
